### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Jmeyer1292** [stegua/MyBlogEntries#1]
Greetings,

I realize it's been a long time since these were updated, but I recently read your blog and used some of the sample code to implement my own Dijkstra's search using Boost.Heap for robot motion planning ([here](https://github.com/ros-industrial-consortium/descartes/pull/179)).

Our existing work is open-source under the Apache 2.0 license. Is there any chance you can update your code with a license? I want to be completely straightforward about the source of my inspiration. :smile:

**Comment by stegua** [comment]
Dear Jmeyer1292,
I will update the source with a very "liberal" license, don't worry, though I am not expert on licenses.
Since the code you use is based on Boost, the Boost license should be good enough, right?

**Comment by stegua** [comment]
It took me a while, but I have upload a MIT License for all this repository that include the Dijkastra source code. Is it ok?
